sudo: required
language: generic
service: 
 - docker

before_install:
 - docker build -t mitanjalic/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true mitanjalic/docker-react npm run test
